#Aliases
alias desktop='cd /mnt/c/Users/atone/Desktop'
alias Desktop='cd /mnt/c/Users/atone/Desktop'
alias downloads='cd /mnt/c/Users/atone/Downloads'
alias Downloads='cd /mnt/c/Users/atone/Downloads'
alias ls='ls -lh --group-directories-first'
alias lsa='ls -alh --group-directories-first'
alias course='cd /mnt/c/Users/atone/Desktop/github-repos/DPU_CYBERSEC/2019/SQ19_TDC405'
alias dpu='cd /mnt/c/Users/atone/Desktop/github-repos/DPU_CYBERSEC'
alias wiki='cd /mnt/c/Users/atone/Desktop/github-repos/DPU_CYBERSEC/DPU_CYBERSEC.wiki'
alias mywiki='cd /mnt/c/Users/atone/Desktop/github-repos/django-apps/ && . env/bin/activate && cd testsite/'
